plugins {
    id "com.android.application"
    id "com.google.gms.google-services"
}

android {
    namespace "com.taskguard"
    compileSdk 35

    defaultConfig {
        applicationId "com.taskguard"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation platform("com.google.firebase:firebase-bom:33.1.2")
    implementation "com.google.firebase:firebase-auth"
    implementation "com.google.firebase:firebase-firestore"
    implementation "androidx.recyclerview:recyclerview:1.3.2"
}
